create table PRO(PRO_COD number(3),
PRO_DES varchar2(50),
primary key (PRO_COD));


create table MUN(
MUN_COD number(3) not null,
MUN_DES varchar2(50) null,
MUN_HAB number(10) null,
MUN_PRO number(3) null,
primary key (MUN_COD),
constraint FK_MUN_PRO foreign key (MUN_PRO) references PRO(PRO_COD));


INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(1,'ARAVA/ALAVA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(2,'ALBACETE');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(3,'ALICANTE/ALACANT');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(4,'ALMERIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(5,'ÁVILA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(6,'BADAJOZ');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(7,'BALEARES/BALEARS');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(8,'BARCELONA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(9,'BURGOS');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(10,'CÁCERES');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(11,'CÁDIZ');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(12,'CASTELLÓN/CASTELLÓ');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(13,'CIUDAD REAL');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(14,'CÓRDOBA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(15,'LA CORUÑA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(16,'CUENCA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(17,'GIRONA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(18,'GRANADA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(19,'GUADALAJARA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(20,'GUIPÚZCOA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(21,'HUELVA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(22,'HUESCA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(23,'JAÉN');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(24,'LEÓN');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(25,'LÉRIDA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(26,'LA RIOJA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(27,'LUGO');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(28,'MADRID');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(29,'MÁLAGA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(30,'MURCIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(31,'NAVARRA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(32,'ORENSE');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(33,'ASTURIAS');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(34,'PALENCIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(35,'LAS PALMAS');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(36,'PONTEVEDRA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(37,'SALAMANCA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(38,'SANTA CRUZ DE TENERIFE');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(39,'CANTABRIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(40,'SEGOVIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(41,'SEVILLA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(42,'SORIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(43,'TARRAGONA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(44,'TERUEL');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(45,'TOLEDO');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(46,'VALENCIA/VALÉNCIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(47,'VALLADOLID');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(48,'VIZCAYA/BIZKAIA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(49,'ZAMORA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(50,'ZARAGOZA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(51,'CEUTA');
INSERT INTO PRO(PRO_COD, PRO_DES) VALUES(52,'MELILLA');

