BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CURSO_APELLIDOS';
EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CURSO_APELLIDOS
(
  APELLIDO  VARCHAR2(128)
);
/

Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('GARCIA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('GONZALEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('RODRIGUEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('FERNANDEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('SANCHEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('PEREZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('MARTINEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('LOPEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('MARTIN');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('GOMEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('HERNANDEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('LARRAÑAGA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('GARMENDIA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ALONSO');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('JIMENEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('RUIZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ALVAREZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('AGUIRRE');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ALBERDI');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ECHEVERRIA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ETXEBERRIA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ARAMBURU');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('MENDIZABAL');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('LASA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('MUÑOZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('GUTIERREZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('DIAZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('MORENO');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ZABALA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('MUGICA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('BLANCO');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('DOMINGUEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('AIZPURUA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ARRIETA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('IGLESIAS');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('RAMOS');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('DIEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ODRIOZOLA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('SANZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('VAZQUEZ');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ROMERO');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ALTUNA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('GIL');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('CALVO');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('AGIRRE');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('JAUREGUI');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('URANGA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ZABALETA');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('ARREGUI');
Insert into CURSO_APELLIDOS
   (APELLIDO)
 Values
   ('OLAIZOLA');
   
INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALONSO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NAVARRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('TORRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DOMINGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VAZQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMIREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SERRANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BLANCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOLINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORALES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SUAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DELGADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUBIO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NUÑEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('IGLESIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MEDINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARRIDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CORTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTILLO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOZANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUERRERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PRIETO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MENDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CALVO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CRUZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GALLEGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VIDAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LEON');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERRERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEÑA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FLORES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CABRERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CAMPOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FUENTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CARRASCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CABALLERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NIETO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('REYES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AGUILAR');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PASCUAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERRERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTANA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LORENZO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MONTERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HIDALGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('IBAÑEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERRER');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DURAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTIAGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VICENTE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BENITEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ARIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VARGAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CARMONA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CRESPO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PASTOR');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SOTO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SAEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VELASCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOYA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SOLER');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ESTEBAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PARRA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BRAVO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GALLARDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROJAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LARRAÑAGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARMENDIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALONSO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AGUIRRE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALBERDI');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ECHEVERRIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ETXEBERRIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ARAMBURU');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MENDIZABAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LASA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ZABALA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUGICA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BLANCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DOMINGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AIZPURUA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ARRIETA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('IGLESIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ODRIOZOLA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VAZQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALTUNA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CALVO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AGIRRE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JAUREGUI');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('URANGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ZABALETA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ARREGUI');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('OLAIZOLA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DOMINGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VAZQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DELGADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARRIDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CARRASCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CAMACHO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMIREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MACIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CRUZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SUAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NUÑEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FLORES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PONCE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('QUINTERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CORDERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('REYES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PRIETO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BORRERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FRANCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NAVARRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BARROSO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTILLA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GRACIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERRER');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PUEYO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUR');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('TORRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CAMPO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NAVARRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CALVO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BUIL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTILLO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('OLIVAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ESCARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ARA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALLUE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BALLARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('IBARZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PASCUAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PALACIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PARDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ABADIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VILLACAMPA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ARNAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SERRANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LATORRE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VIÑUALES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTOLARIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LANAU');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('TORRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOLINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARRIDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SERRANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CRUZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMIREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('EXPOSITO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTILLO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CORTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LARA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('QUESADA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MEDINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DELGADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FUENTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORALES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NAVARRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERRERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('COBO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CABRERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOYA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HIDALGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CAMPOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PADILLA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CONTRERAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CARRILLO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALONSO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BLANCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PRIETO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ARIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SUAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DOMINGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROBLES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARCOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NUÑEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MENDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VIDAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUBIO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FUERTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VAZQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('IGLESIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FRANCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CRESPO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALLER');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MIGUELEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LLAMAZARES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GALLEGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERRERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FIDALGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PRADA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('REDONDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CALVO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DE LA FUENTE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOLINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HEREDIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORALES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('TORRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTILLO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CORTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NAVARRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUERRERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMIREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MEDINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CARMONA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MALDONADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DELGADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SERRANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTIAGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AGUILERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOZANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARRIDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALONSO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VILCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOYA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROBLES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VARGAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERRERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROLDAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DOMINGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VAZQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DELGADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMIREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NAVARRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('TORRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LEON');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CARMONA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NUÑEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORALES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUERRERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BENITEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HIDALGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SUAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AGUILAR');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('REYES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BLANCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SERRANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOLINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VARGAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARRIDO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERRERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MONTERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('VICENTE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARCOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALONSO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANTOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HERRERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BENITO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MATEOS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('IGLESIAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DOMINGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BLANCO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CALVO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PRIETO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NIETO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BLAZQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FRAILE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DELGADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MONTERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MIGUEL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GIL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ANDRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GALLEGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RIVAS');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BERNAL');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUBIO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LORENZO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BARBERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('TORRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FUENTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GARCIA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LOPEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JIMENEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SANCHEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PEREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RODRIGUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('FERNANDEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MUÑOZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GOMEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GONZALEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORENO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROMERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTINEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LUQUE');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('SERRANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DIAZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RAMIREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MOLINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CASTRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('JURADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MORALES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CARMONA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTIZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARTIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('GUTIERREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('TORRES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CABALLERO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('DELGADO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LEON');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AGUILAR');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('REYES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ROLDAN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('AGUILERA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('NAVARRO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARQUEZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('HIDALGO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MARIN');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LUNA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('BAENA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ORTEGA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('PRIETO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('RUBIO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('ALVAREZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MEDINA');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('MONTES');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CANO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CABELLO');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('CRUZ');
/

INSERT INTO CURSO_APELLIDOS (APELLIDO) VALUES ('LARA');
/


COMMIT;
