
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CURSO_CALLES';
EXCEPTION 
   WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE CURSO_CALLES
(
   ID       NUMBER(22),
   TIPO_VIA CHAR(2),
   CALLE    VARCHAR2(128)
);
/

ALTER TABLE CURSO_CALLES ADD (PRIMARY KEY (ID) ENABLE VALIDATE);
/


INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3962, 'AV', 'ANDALUCIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3841, 'AV', 'BLAS INFANTE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4032, 'AV', 'CARLOS CANO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4167, 'AV', 'DE ESPAÑA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4077, 'AV', 'DEL COMERCIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4078, 'AV', 'INDUSTRIA (DE LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3965, 'AV', 'MAIRENA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3904, 'AV', 'PAZ (LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3906, 'AV', 'PIEDRA DEL GALLO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3976, 'AV', 'REPUBLICA DE NICARAGUA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3943, 'AV', 'TABLADA (LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3947, 'AV', 'TINAJAS (DE LAS)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3964, 'AV', 'TRABAJO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4161, 'CL', 'ACEBUCHE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3959, 'CL', 'ACEBUCHINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3846, 'CL', 'ADRIANO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4113, 'CL', 'AGRICULTORES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3850, 'CL', 'AGUA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4068, 'CL', 'ALAMO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4074, 'CL', 'ALBAHACA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3796, 'CL', 'ALBAICIN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3791, 'CL', 'ALBERO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4089, 'CL', 'ALC. JOSE ROLDAN VERGARA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4107, 'CL', 'ALCAICERIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4048, 'CL', 'ALCALA DE GUADAIRA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3795, 'CL', 'ALCALDE GIL LOPEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3798, 'CL', 'ALCALDE LEON RIOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3805, 'CL', 'ALCORES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4080, 'CL', 'ALCORNOQUE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4129, 'CL', 'ALEGRIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4092, 'CL', 'ALEJANDRO GUICHOT SIERRA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4116, 'CL', 'ALEMANIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3941, 'CL', 'ALFARERIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4177, 'CL', 'ALFAREROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4093, 'CL', 'ALFONSO LASSO DE LA VEGA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4085, 'CL', 'ALGARROBO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3792, 'CL', 'ALHELI');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4076, 'CL', 'ALHUCEMA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4162, 'CL', 'ALICATADORES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3986, 'CL', 'ALMAGRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3897, 'CL', 'ALMERIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4103, 'CL', 'ALMUTAMID');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3988, 'CL', 'ALUNADA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3804, 'CL', 'ALVAREZ QUINTERO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3989, 'CL', 'AMARGURA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3809, 'CL', 'AMISTAD');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3851, 'CL', 'ANDRES SEGOVIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4134, 'CL', 'AP CORREOS NUMERO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3934, 'CL', 'ARCILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3857, 'CL', 'ARIAS DE SAAVEDRA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4071, 'CL', 'ARRAYAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3793, 'CL', 'ARROYO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4056, 'CL', 'ARROYO DE ALCAUDETE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4016, 'CL', 'ARROYO DE LA ALCANTARILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4055, 'CL', 'ARROYO DE LA CHOBA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3806, 'CL', 'AUTONOMIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4101, 'CL', 'AVERROES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3803, 'CL', 'AZAHAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4169, 'CL', 'BAMBERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3939, 'CL', 'BARRERIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3862, 'CL', 'BEATRIZ RAMIREZ MENDOZA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3967, 'CL', 'BECQUER');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4117, 'CL', 'BELGICA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3808, 'CL', 'BOTICA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4153, 'CL', 'CABEZADAS DEL MOSCOSO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3817, 'CL', 'CADIZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3931, 'CL', 'CALDERON DE LA BARCA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3811, 'CL', 'CALVARIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4021, 'CL', 'CAMINO DE CAMPOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4064, 'CL', 'CAMINO DE LOS HARAGANES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4020, 'CL', 'CAMINO DE NEBLINES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4065, 'CL', 'CAMINO DE PIEDRA AZUL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3823, 'CL', 'CAMINO DEL MOSCOSO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4058, 'CL', 'CANTARRANAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3937, 'CL', 'CANTERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4171, 'CL', 'CANTIÑA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3825, 'CL', 'CARLOS MENDEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4099, 'CL', 'CARMEN AMAYA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3813, 'CL', 'CARMONA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3983, 'CL', 'CARNICEROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3982, 'CL', 'CARPINTEROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4019, 'CL', 'CARRIL DEL AGUARDIENTE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4156, 'CL', 'CAÑA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3821, 'CL', 'CAÑALIZO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3800, 'CL', 'CEMENTERIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4082, 'CL', 'CEREZO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4018, 'CL', 'CERRO DE LA MOTILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4062, 'CL', 'CERRO DEL PARADOR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4066, 'CL', 'CERROS BLANCOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4061, 'CL', 'CERROS DE GALEOTE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4052, 'CL', 'CERROS DEL DUENDE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3866, 'CL', 'CERVANTES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4059, 'CL', 'CHAPATAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4024, 'CL', 'CLARA CAMPOAMOR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3810, 'CL', 'CLAVEL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3815, 'CL', 'COLON');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4090, 'CL', 'CONC. JOSE JIMENEZ MARTIN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3799, 'CL', 'CONDE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3993, 'CL', 'CONDE DE CASTELLAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3827, 'CL', 'CONVENTO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3801, 'CL', 'CORBONES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3830, 'CL', 'CORDOBA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3816, 'CL', 'CORRALES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3963, 'CL', 'CORREDERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4112, 'CL', 'COSTURERAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4166, 'CL', 'CRISTALEROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4038, 'CL', 'CRISTINA DEL VALLE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3969, 'CL', 'CRISTO DE LA MISERICORDIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3835, 'CL', 'CRISTO DE LA VERACRUZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3999, 'CL', 'CRISTO DEL AMOR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4115, 'CL', 'CRISTOBAL DE MORALES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3966, 'CL', 'CRUZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3990, 'CL', 'CRUZ DEL MORO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3818, 'CL', 'CUATRO DE DICIEMBRE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3824, 'CL', 'DALI');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3944, 'CL', 'DARRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4108, 'CL', 'DE LA ANTIGUA ACADEMIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4164, 'CL', 'DE LOS ALMOHADES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4104, 'CL', 'DE LOS ALMORAVIDES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4105, 'CL', 'DE LOS MOZARABES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4163, 'CL', 'DE LOS MUDEJARES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4180, 'CL', 'DE LOS NAZARIES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4106, 'CL', 'DE LOS TAIFAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4121, 'CL', 'DINAMARCA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3826, 'CL', 'DOCTOR FLEMING');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3991, 'CL', 'DOS DE MAYO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4095, 'CL', 'DOÑA CARMEN LOPEZ JIMENEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4109, 'CL', 'ELECTRICISTAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4083, 'CL', 'ENCINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3831, 'CL', 'ESCUELAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4179, 'CL', 'FANDANGO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3833, 'CL', 'FEDERICO GARCIA LORCA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3819, 'CL', 'FERIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3955, 'CL', 'FERMIN SALVOCHEA ALVAREZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4181, 'CL', 'FERNANDO VILLALON');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4111, 'CL', 'FONTANEROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4120, 'CL', 'FRANCIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3954, 'CL', 'FRANCISCO GALVAN GARCIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4155, 'CL', 'FRANCISCO GUERRERO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3970, 'CL', 'FRANCISCO IRIBARREN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3843, 'CL', 'FRATERNIDAD');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3980, 'CL', 'FRAY BARTOLOME LAS CASAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4084, 'CL', 'FRESNO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3945, 'CL', 'FUENTESOL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3974, 'CL', 'GABRIEL Y GALAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4017, 'CL', 'GAMONALES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3872, 'CL', 'GASPAR JUAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4002, 'CL', 'GIBRALTAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3878, 'CL', 'GOMEZ DE RIVERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3957, 'CL', 'GORDAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3834, 'CL', 'GOYA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3853, 'CL', 'GRANADA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4001, 'CL', 'GRANADO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4014, 'CL', 'GRANAINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4122, 'CL', 'GRECIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3836, 'CL', 'GRECO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3996, 'CL', 'GUADAIRA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3968, 'CL', 'GUADALETE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3998, 'CL', 'GUADALQUIVIR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4051, 'CL', 'HAZAS DE LA VEGUETA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4060, 'CL', 'HAZAS LARGAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4157, 'CL', 'HERMANOS CALABUIG');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3977, 'CL', 'HERMANOS MACHADO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3985, 'CL', 'HERMANOS PINZON');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4079, 'CL', 'HERREROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4086, 'CL', 'HIGUERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4118, 'CL', 'HOLANDA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3973, 'CL', 'HONDILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4005, 'CL', 'HORNO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4114, 'CL', 'HORTELANOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3864, 'CL', 'HUELVA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4030, 'CL', 'HUERTA DAZA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4039, 'CL', 'HUERTA DE BERNABE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4029, 'CL', 'HUERTA DEL MARQUES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3807, 'CL', 'HUERTA DEL MILITAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4044, 'CL', 'HUERTA EL CONDE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4159, 'CL', 'HUERTA EL CURA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4026, 'CL', 'HUERTA EL GACHA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4040, 'CL', 'HUERTA EL MELI');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4013, 'CL', 'HUERTA EL VICARIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4028, 'CL', 'HUERTA GASPAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4034, 'CL', 'HUERTA LA CHISPA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4033, 'CL', 'HUERTA LA PIJURICA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4031, 'CL', 'HUERTA LAS MERRAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4027, 'CL', 'HUERTA MARINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4037, 'CL', 'HUERTA MORE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4025, 'CL', 'HUERTA PINO GRANDE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4035, 'CL', 'HUERTA SANTA JULIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4043, 'CL', 'HUERTA TIO PIPIRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4041, 'CL', 'HUERTA VIÑA DON JUAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3837, 'CL', 'HUERTAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4023, 'CL', 'HUERTO PONCE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3898, 'CL', 'INCA GARCILASSO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4009, 'CL', 'INVIERNO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4124, 'CL', 'IRLANDA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3951, 'CL', 'ISAAC ALBENIZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3994, 'CL', 'ISAAC PERAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4119, 'CL', 'ITALIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3869, 'CL', 'JAEN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4072, 'CL', 'JARA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3829, 'CL', 'JAZMIN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3979, 'CL', 'JEREZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3848, 'CL', 'JIMENEZ MUÑOZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3849, 'CL', 'JOAN MIRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3885, 'CL', 'JOAQUIN TURINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4046, 'CL', 'JOSE BERMEJO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3844, 'CL', 'JUAN BAUTISTA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3790, 'CL', 'JUAN DE LA COSA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3875, 'CL', 'JUAN RAMON JIMENEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3995, 'CL', 'JUAN SEBASTIAN ELCANO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3972, 'CL', 'JUAN XXIII');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4075, 'CL', 'JUNCIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3889, 'CL', 'LAGUNA (LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3892, 'CL', 'LEPANTO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3832, 'CL', 'LIRIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4047, 'CL', 'LIVIANAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3880, 'CL', 'LOPE DE VEGA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4098, 'CL', 'LUIS CERNUDA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3894, 'CL', 'LUMBRERAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3895, 'CL', 'MAESTRO GRANADO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3901, 'CL', 'MAESTRO NAVARRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3997, 'CL', 'MAESTRO SERI');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4102, 'CL', 'MAIMONIDES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3886, 'CL', 'MALAGA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4160, 'CL', 'MALVASIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3903, 'CL', 'MANUEL DE FALLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3860, 'CL', 'MANUEL DE LOS SANTOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3867, 'CL', 'MANUEL J GARCIA CAPARROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3870, 'CL', 'MANUEL JIMENEZ LEON');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4128, 'CL', 'MANUELA SANCHEZ SANTOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3874, 'CL', 'MARIA EMILIA MUÑOZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4042, 'CL', 'MARIA GALIANA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4045, 'CL', 'MARIANA PINEDA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4132, 'CL', 'MARTINETE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4165, 'CL', 'MECANICOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3905, 'CL', 'MERCED (LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3890, 'CL', 'MIGUEL HERNANDEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3839, 'CL', 'MILOJA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4168, 'CL', 'MINERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4053, 'CL', 'MOLINOS DE ALCAUDETE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3842, 'CL', 'MUELA (LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3876, 'CL', 'MURILLO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3881, 'CL', 'NAJERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4004, 'CL', 'NARANJO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4094, 'CL', 'NICASIA CAMPILLO ROLDAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4088, 'CL', 'NOGAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3975, 'CL', 'NTRO PADRE JESUS NAZARENO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4006, 'CL', 'NUEVA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4000, 'CL', 'NUÑEZ DE BALBOA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3883, 'CL', 'ODONNELL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4007, 'CL', 'OLIVO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3896, 'CL', 'OTOÑO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3910, 'CL', 'PABLO CASALS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3913, 'CL', 'PADRE ANTONIO SOLER');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4054, 'CL', 'PAGO DE VIÑAS VIEJAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4049, 'CL', 'PAGO DEL PARRAMON');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4022, 'CL', 'PAGO LA ASOMADILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3865, 'CL', 'PALMA (LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4081, 'CL', 'PALMERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4067, 'CL', 'PANADEROS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3899, 'CL', 'PARQUE DE LA CONSTITUCION');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4097, 'CL', 'PASAJE DE LOS MOLINOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3953, 'CL', 'PEDRO GARCIA CARRASCO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3887, 'CL', 'PICASSO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4087, 'CL', 'PINO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3847, 'CL', 'PINTOR JUAN ROLDAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4133, 'CL', 'PINTORES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3971, 'CL', 'PIZARRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3891, 'CL', 'PLACIDO FERNANDEZ VIAGAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4015, 'CL', 'POCITO SACO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3828, 'CL', 'POLIGONO LA MUELA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3914, 'CL', 'POZO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4012, 'CL', 'POZO PROLONGACION');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4057, 'CL', 'PRADO DE LOS CABALLOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3908, 'CL', 'PRIMAVERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3911, 'CL', 'QUEVEDO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3952, 'CL', 'RAFAEL SOTO MAYOR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3987, 'CL', 'RAFAELA HERRERA RUIZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3981, 'CL', 'RAMON Y CAJAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3956, 'CL', 'RAPAZALLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3922, 'CL', 'REAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4110, 'CL', 'RECOVERAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4123, 'CL', 'REINO UNIDO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3893, 'CL', 'RIBERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3822, 'CL', 'RIO GENIL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4003, 'CL', 'RODRIGO DE TRIANA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3918, 'CL', 'ROMA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4125, 'CL', 'ROMANCE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4069, 'CL', 'ROMERO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3916, 'CL', 'RONDA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3855, 'CL', 'RONQUERA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3919, 'CL', 'ROQUETAS DE MAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3852, 'CL', 'ROSAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3978, 'CL', 'ROSARIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4091, 'CL', 'S. JUAN BAUTISTA DELGADO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4131, 'CL', 'SAETA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3856, 'CL', 'SALADO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4127, 'CL', 'SALUD MUÑOZ LOPEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3859, 'CL', 'SAN CARLOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3923, 'CL', 'SAN JOSE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3924, 'CL', 'SAN JUAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3928, 'CL', 'SAN LAUREANO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3929, 'CL', 'SAN LUCAS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3932, 'CL', 'SAN MARCOS');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3933, 'CL', 'SAN MATEO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3936, 'CL', 'SAN PABLO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3938, 'CL', 'SAN PEDRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3877, 'CL', 'SAN PEDRO NOLASCO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4008, 'CL', 'SANTA ANA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3921, 'CL', 'SANTA LUCIA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3882, 'CL', 'SANTA MARIA DEL ALCOR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3940, 'CL', 'SANTIAGO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4126, 'CL', 'SEGUIRIYA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3900, 'CL', 'SEGUNDO JIMENEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3942, 'CL', 'SENECA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3902, 'CL', 'SEVERO OCHOA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3861, 'CL', 'SEVILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3863, 'CL', 'SOL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3907, 'CL', 'SOROLLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4154, 'CL', 'TARANTA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3935, 'CL', 'TEJARES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3946, 'CL', 'TEODOSIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3868, 'CL', 'TIO PINTO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3925, 'CL', 'TIRSO DE MOLINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3909, 'CL', 'TOCINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4070, 'CL', 'TOMILLO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3950, 'CL', 'TRAJANO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3873, 'CL', 'TREN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3927, 'CL', 'UNIDAD');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3912, 'CL', 'VALDES LEAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4010, 'CL', 'VALDIVIDA''');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3915, 'CL', 'VEINTIOCHO DE FEBRERO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3917, 'CL', 'VELAZQUEZ');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3930, 'CL', 'VERANO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4170, 'CL', 'VERDIALES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4050, 'CL', 'VEREDA DE SEVILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4063, 'CL', 'VEREDA DEL BAILAOR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3984, 'CL', 'VIAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3884, 'CL', 'VIRGEN DE LOS DOLORES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3888, 'CL', 'VIRGEN DEL MAYOR DOLOR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4073, 'CL', 'YERBABUENA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4176, 'CL', 'ZORZALEÑA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3920, 'CL', 'ZURBARAN');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3961, 'CM', 'CERRO EL TUNO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3802, 'CM', 'ESTACION DE LA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3812, 'CM', 'HUERTAS (DE LAS)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3814, 'CM', 'JUAN PIPIRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3820, 'CM', 'LADERAS DEL CALVARIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3838, 'CM', 'VEREDA ALUNADA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4100, 'CR', 'CARRETERA CALVARIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3949, 'CR', 'TOCINA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4096, 'PG', 'ACEQUIAS (LAS)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3794, 'PZ', 'ALJARAFE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3797, 'PZ', 'AYUNTAMIENTO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3858, 'PZ', 'BASTILIPPO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3926, 'PZ', 'CADENAS (LAS)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4130, 'PZ', 'FEDERICA MONTSENY');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4036, 'PZ', 'GRANADILLO (DEL)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3879, 'PZ', 'ITALICA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4158, 'PZ', 'JERUSALEN (DE)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3854, 'PZ', 'JULIO ROMERO DE TORRES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3840, 'PZ', 'MEXICO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4011, 'PZ', 'RAFAEL ALBERTI');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3871, 'PZ', 'SACRISTAN GUERRERO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3948, 'PZ', 'SOL (DEL)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3958, 'UR', 'EL BALCON DE LOS ALCORES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3960, 'UR', 'EL MANANTIAL');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (3845, 'UR', 'VISTA VERDE');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4149, 'AV', 'TRABAJO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4151, 'CL', 'DESCONOCIDO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4174, 'CL', 'MANZANILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4150, 'CL', 'PROLONGACION POZO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4136, 'CM', 'CEMENTERIO (DEL)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4148, 'CM', 'CERRO PEREA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4137, 'CM', 'ESTACION (LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4138, 'CM', 'HUERTA EL MILITAR');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4139, 'CM', 'HUERTAS (LAS)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4140, 'CM', 'JUAN PIPIRO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4141, 'CM', 'LADERAS DEL CALVARIO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4142, 'CM', 'MOSCOSO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4144, 'CM', 'VEREDA ALUNADA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4143, 'PA', 'MUELA (DE LA)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4172, 'PZ', 'DIPUTACION DE SEVILLA');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4173, 'PZ', 'MANUEL CASTILLO');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4146, 'UR', 'BALCON DE LOS ALCORES');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4135, 'UR', 'BANCALES (LOS)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4147, 'UR', 'MANANTIAL (EL)');
INSERT INTO CURSO_CALLES
   (ID, TIPO_VIA, CALLE)
 VALUES
   (4145, 'UR', 'VISTA VERDE');
COMMIT;
